Travel-WithMe/TravelWithMe-sever

- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/controller/FeedController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/entity/Feed.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/repository/FeedRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/service/FeedService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/controller/MemberController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/entity/Member.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/repository/MemberRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/service/MemberService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recuirtmentbuddy/controller/BuddyMatchingController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recuirtmentbuddy/controller/RecuirtmentBuddyController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recuirtmentbuddy/entity/BuddyMatching.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recuirtmentbuddy/entity/RecuirtmentBuddy.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recuirtmentbuddy/repository/BuddyMatchingRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recuirtmentbuddy/repository/RecuirtmentBuddyRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recuirtmentbuddy/service/BuddyMatchingService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recuirtmentbuddy/service/RecuirtmentBuddyService.java
> [feat -> develop] rename - #3: 도메인 패키지 구조 설계

- travel-with-me/src/test/java/com/frog/travelwithme/intergration/example.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/controller/AbstractMemberController.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/controller/delete/MemberControllerDeleteTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/controller/get/MemberControllerGetTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/controller/patch/MemberControllerPatchTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/controller/post/MemberControllerPostTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/repository/AbstractMemberRepository.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/repository/MemberRepositoryTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/service/AbstractMemberService.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/service/MemberServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/ApiDocumentUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/ObjectMapperUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/reqeust/ResultActionsUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/resource/CommunityResourceUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/resource/ResourceUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/response/ResponseErrorSnippet.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/response/ResponsePageSnippet.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/response/ResponsePostSnippet.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/security/WithMockCustomUser.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/security/WithMockCustomUserSecurityContextFactory.java
1. 테스트 코드 패키지 및 구조 설계
2. 임시 테스트코드 작성
테스트 코드를 작성하기 위한 구조 설계 및 편의 클래스를 생성하였습니다.
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] rename - #5: 테스트코드 구조 설계

- travel-with-me/src/main/java/com/frog/travelwithme/common/EnumCollection.java
- travel-with-me/src/main/java/com/frog/travelwithme/common/EnumType.java
</br>
Enum 정보를 한군데에서 모아서 수집할 수 있는 클래스를 작성하였습니다.  
메서드 추상화를 통해 상속받아 관리할 수 있습니다.
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #11: Enum 데이터 취합 클래스 작성

- travel-with-me/build.gradle
- travel-with-me/src/main/java/com/frog/travelwithme/common/config/EmbeddedRedisConfig.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
> [feat -> develop] feat - #17: Embedded Redis 구현 및 Redis Test

- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/entity/Member.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/service/MemberService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/config/AES128Config.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/config/EmbeddedRedisConfig.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/config/PasswordEncoderConfig.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/config/RedisConfig.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumType.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/security/auth/filter/JwtAuthenticationFilter.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/security/auth/service/AuthService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/security/auth/utils/CustomAuthorityUtils.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/security/config/SecurityConfiguration.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/utils/CustomBeanUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/common/config/AES128ConfigTest.java
> [feat -> develop] rename - #19: 패키지 구조 변경

- travel-with-me/.gitignore
- travel-with-me/build.gradle
1. gradle 파일 수정 (복사설정)
2. .gitignore dev.yml 설정
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #21: submodule gradle, gitignore

- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/repository/MemberRepositoryTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/service/MemberServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
1. Member Service 단위 테스트
2. Member Repository 단위 테스트
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] test - 31: Member 단위 테스트(Service, Respository)

- travel-with-me/.gitignore
- travel-with-me/src/docs/asciidoc/index.adoc
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/member/MemberIntegrationTest.java
> [feat -> develop] feat - #40: Member, Auth API 문서 생성

- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/controller/BuddyMatchingController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/controller/BuddyRecruitmentController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/controller/dto/BuddyDto.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/entity/BuddyMatching.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/entity/BuddyRecruitment.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/mapper/BuddyMapper.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/repository/BuddyMatchingCustomRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/repository/BuddyMatchingCustomRepositoryImpl.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/service/BuddyMatchingService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/service/BuddyRecruitmentService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/dto/MessageResponseDto.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ErrorResponse.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/auth/AuthIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddyrecruitment/BuddyMatchingIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddyrecruitment/BuddyRecruitmentIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/member/MemberIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/controller/BuddyMatchingControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/controller/BuddyRecruitmentControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/repository/BuddyMatchingRepositoryTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/repository/BuddyRecruitmentRepositoryTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/service/BuddyMatchingServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/ObjectMapperUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/snippet/response/ResponseSnippet.java
- 리펙토링 
1. recruitmentIdsId -> recruitmentId 오타 변경
2. 동행신청 작성,수정,조회 응답데이터 id 추가
3. ResponseSnippet Data 추가
4. ObjectMapperUtils 메서드 추가
5. BuddyRecruitment.java 연관관계 설정 (BuddyMatching)
6. BuddyRecruitment 통합테스트 동행작성 부분 id 검증 추가 및 줄정
7. BuddyRecruitmentRepositoryTest 수정 테스트케이스 보강
8. ErrorResponse 기본생성자 추가
9. StubData Member OAuth정보 추가 및 매칭데이터 추가
- 매칭신청 작업 
1. 동행 매칭신청 API 설계 및 서비스 로직작성
2. 동행 매칭신청 Integration Test 케이스 작성 및 테스트 완료
3. 동행 매칭신청 Unit Test 케이스 작성 및 테스트 완료
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #38: 동맹 매칭 신청 구현

- travel-with-me/src/docs/asciidoc/index.adoc
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddyrecuirtment/mapper/BuddyMapper.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/controller/MemberController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/controller/dto/MemberDto.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/entity/Member.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/mapper/MemberMapper.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/service/MemberService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/auth/AuthIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddyrecruitment/BuddyRecruitmentIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/member/MemberIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/controller/MemberControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/service/MemberServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/ResultActionsUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/snippet/reqeust/RequestSnippet.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/snippet/response/ResponseSnippet.java
1. image 파일 form-data로 전달받도록 수정
2. 회원가입, 회원 정보 수정 로직 gender 필드 추가
3. 회원 profile image 수정 API 추가
4. Member Controller, Service 단위 테스트
5. Member 통합 테스트
6. RestDocs API 문서 업데이트
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #40: Member 로직 리팩토링

- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/BuddyIntegrationTest.java
1. 테스트 코드 스니핏 이름 수정
2. 취소시 검증 오류 코드 수정
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #44 : 동행 매칭 취소 테스트 코드 오류 수정

- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/controller/BuddyController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/entity/Buddy.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/BuddyCustomRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/BuddyCustomRepositoryImpl.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/service/BuddyService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/controller/RecruitmentController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/entity/Recruitment.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/repository/RecruitmentCustomRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/repository/RecruitmentCustomRepositoryImpl.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/repository/RecruitmentRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/recruitment/service/RecruitmentService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/BuddyIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/controller/BuddyControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/repository/BuddyRepositoryTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/service/BuddyServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/recruitment/controller/RecruitmentControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/recruitment/repository/RecruitmentRepositoryTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/recruitment/service/RecruitmentServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
1. Recruitment id 조회 Member Join하여 조회하도록 추가
2. 메서드 명명 변경 (ByUser -> ByEmail)
3. 동행 승인 API 작성
4. 동행 승인 테스트 코드 작성 (Integration, Unit)
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #51 : 동행 매칭 승인 API 작성

- .github/workflows/gradle.yml
1. gradle 오타 수정
</br>
어떤 변경 사항이 있나요?
> [patch -> develop] chore - #56: Update gradle.yml

- .github/workflows/gradle.yml
1. CodeDeploy 설정 추가
</br>
어떤 변경 사항이 있나요?
> [develop -> main] feat - #56: CodeDeploy 설정 추가

- .github/workflows/gradle.yml
1. dev.yml 서버 설정 파일 내용 추가
2. workflows 업데이트 merge
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #65: dev.yml 설정 및 머지 커밋 update

- .github/workflows/gradle.yml
1. dev.yml 서버 설정 파일 내용 추가
2. workflows 업데이트 merge
</br>
어떤 변경 사항이 있나요?
> [develop -> main] feat - #65: dev.yml 설정 및 머지 커밋 update

- travel-with-me/src/test/java/com/frog/travelwithme/TravelWithMeApplicationTests.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/security/auth/controller/AuthControllerTest.java
1. Test 코드 프로파일링 안된 것으로 추정되어 수정
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #65: Git actions 빌드 에러수정

- .github/workflows/gradle.yml
- travel-with-me/src/test/java/com/frog/travelwithme/TravelWithMeApplicationTests.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/security/auth/controller/AuthControllerTest.java
1. Test 코드 프로파일링 안된 것으로 추정되어 수정
</br>
어떤 변경 사항이 있나요?
> [develop -> main] feat - #65: Git actions 빌드 에러수정

- .github/workflows/gradle.yml
- travel-with-me/src/test/java/com/frog/travelwithme/unit/common/config/AES128ConfigTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/security/auth/controller/AuthControllerTest.java
1. SpringBootTest 코드 어노테이션 부분 Active Profie Test 추가
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #65: CI/CD build시 test 코드 오류 수정

- travel-with-me/src/test/java/com/frog/travelwithme/unit/common/config/AES128ConfigTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/security/auth/controller/AuthControllerTest.java
1. test 코드 프로파일링 안되어 git actions build시 오류 발생 수정
</br>
어떤 변경 사항이 있나요?
> [develop -> main] feat - #65: CI/CD build시 test 코드 오류 수정

- .github/workflows/gradle.yml
- travel-with-me/src/main/java/com/frog/travelwithme/global/config/EmbeddedRedisConfig.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
1. EC2 서버에서 EmbeddedRedisConfig관련 Bean등록이 되지않아 부트 실패하는 오류 수정
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #65: EmbeddedRedis Profile 오류

- .github/workflows/gradle.yml
- travel-with-me/src/main/java/com/frog/travelwithme/global/config/EmbeddedRedisConfig.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
1. EC2 서버에서 EmbeddedRedisConfig관련 Bean등록이 되지않아 부트 실패하는 오류 수정
</br>
어떤 변경 사항이 있나요?
> [develop -> main] feat - #65: EmbeddedRedis Profile 오류

- .github/workflows/gradle.yml
- travel-with-me/src/main/java/com/frog/travelwithme/global/config/EmbeddedRedisConfig.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
> [develop -> main] feat - #65: rebase 오류수정

- .github/workflows/gradle.yml
> [fix -> develop] fix - #65: merge 오류수정

- .github/workflows/gradle.yml
> [develop -> main] fix - #65: merge 오류수정

- .github/workflows/gradle.yml
- travel-with-me/src/test/java/com/frog/travelwithme/unit/redis/service/RedisCrudTest.java
> [feat -> develop] feat - #65: rebase 오류수정

- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/controller/MatchingController.java
> [test -> develop] test - #83: rebase Test

- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/controller/FeedController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/entity/Feed.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/mapper/FeedMapper.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/service/FeedService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/entity/Member.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/utils/StringListConverter.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/feed/FeedIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/feed/controller/FeedControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/ResultActionsUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/snippet/reqeust/RequestSnippet.java
1. 좋아요, 좋아요 취소 기능 구현
2. MultiPartFile RequestPart 추가
3. isLiked 로직 구현
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #30: Feed 좋아요 기능 구현

- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/controller/MatchingController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/RecruitmentCustomRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/RecruitmentCustomRepositoryImpl.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/service/MatchingService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/service/RecruitmentService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/MatchingIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/controller/MatchingControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/repository/RecruitmentRepositoryTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/service/MatchingServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/service/RecruitmentServiceTest.java
1. 동행 매칭거절 API 및 Service 로직 작성
2. Integration Test, Unit Test 작성 완료
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #55: 동행 매칭거절 API 작성

- travel-with-me/scripts/deploy.sh
1. dev -> prod 환경
2. shellsript profile prod환경 프로파일 하도록 수정
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #93: profile 환경 변경

- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/controller/RecruitmentController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/controller/dto/RecruitmentDto.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/mapper/RecruitmentMapper.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/MatchingCustomRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/MatchingCustomRepositoryImpl.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/RecruitmentCustomRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/repository/RecruitmentCustomRepositoryImpl.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/service/MatchingService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/buddy/service/RecruitmentService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/MatchingIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/RecruitmentIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/controller/RecruitmentControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/repository/MatchingRepositoryTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/repository/RecruitmentRepositoryTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/service/RecruitmentServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/snippet/response/ResponseSnippet.java
</br>
1. 해당 동행 모집글에 신청요청한 회원만 조회하는 API 작성
2. Unit, Integration Test 코드 작성
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #50: 동행 모집글 신청 회원 조회 기능 개발

- travel-with-me/build.gradle
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/controller/FeedController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/controller/dto/FeedDto.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/entity/Feed.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/mapper/FeedMapper.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/service/FeedService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/controller/MemberController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/entity/Member.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/mapper/MemberMapper.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/service/MemberService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/config/AwsS3Config.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/file/AmazonS3ResourceStorage.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/file/FileUploadService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/utils/StringListConverter.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/auth/AuthIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/MatchingIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/RecruitmentIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/feed/FeedIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/member/MemberIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/buddy/service/RecruitmentServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/feed/controller/FeedControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/controller/MemberControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/service/MemberServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/file/AmazonS3ResourceStorageTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/file/FileUploadServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/ResultActionsUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
1. File CRUD 로직 구현
2. S3 연결 및 설정
3. Feed File 로직 추가
4. Member File 로직 추가
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #96: File 업로드, 수정, 삭제 구현. Feed, Member File 로직 추가

- travel-with-me/src/test/java/com/frog/travelwithme/intergration/auth/AuthIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/MatchingIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/RecruitmentIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/feed/FeedIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/member/MemberIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/feed/service/FeedServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
1. Test용 S3 생성
2. 통합 테스트 코드에 Mock S3 시나리오 설정
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] test - #96: Test용 Mock S3 구현

- travel-with-me/src/main/java/com/frog/travelwithme/global/config/AwsS3Config.java
> [feat -> develop] fix - #96: 테스트 오류 해결

- travel-with-me/src/test/java/com/frog/travelwithme/config/MockAwsS3Config.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/member/MemberIntegrationTest.java
1. Member 통합테스트에서 MockAmazonS3의 시나리오를 추가했습니다. (NPE 해결)
2. MockAmamzonS3 메서드에 @Override 애너테이션 추가
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] fix - #96: Member 통합테스트에서 MockAmazonS3 시나리오 추가 (NPE 해결)

- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/entity/Feed.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/service/FeedService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/controller/MemberController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/controller/dto/MemberDto.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/entity/Member.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/mapper/MemberMapper.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/service/MemberService.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/enums/EnumCollection.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/exception/ExceptionCode.java
- travel-with-me/src/main/java/com/frog/travelwithme/global/file/FileUploadService.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/member/MemberIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/service/MemberServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
1. 회원이 저장된 이후 profileImage 저장되도록 수정 
2. Mapping 타임에서 유효성 검사를 진행하던 Gender를 DTO로 받아오는 시점에서 유효성 검사하도록 수정
3. 회원 프로필이미지가 수정된 이후 기존 이미지파일 S3에서 삭제되도록 수정
4. 피드를 DB에 저장 시점에서 예외 발생 시 S3에 저장했던 이미지를 삭제하는 예외처리 로직 추가
5. S3에 이미지 저장되는 로직 처리 후 이전 이미지 삭제 되도록 로직 수정 
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] fix - #105: 트랜잭션을 고려한 S3 Image 로직 처리

- travel-with-me/src/docs/asciidoc/index.adoc
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/controller/MemberController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/controller/dto/MemberDto.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/mapper/MemberMapper.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/repository/MemberRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/service/MemberService.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/auth/AuthIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/MatchingIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/RecruitmentCommentIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/buddy/RecruitmentIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/feed/FeedIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/member/MemberIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/controller/MemberControllerTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/unit/domain/member/service/MemberServiceTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/ResultActionsUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/snippet/reqeust/RequestSnippet.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/snippet/response/ResponseSnippet.java
1.  회원가입 로직에서 프로필 이미지, 자기소개 제거
2. 이메일, 닉네임 중복 체크 API 추가
3. API 문서 업데이트
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #121: 회원가입 로직 수정

- travel-with-me/src/docs/asciidoc/index.adoc
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/controller/FeedController.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/repository/FeedCustomRepository.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/repository/FeedCustomRepositoryImpl.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/feed/service/FeedService.java
- travel-with-me/src/main/java/com/frog/travelwithme/domain/member/entity/Member.java
- travel-with-me/src/test/java/com/frog/travelwithme/intergration/feed/FeedIntegrationTest.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/ResultActionsUtils.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/StubData.java
- travel-with-me/src/test/java/com/frog/travelwithme/utils/snippet/reqeust/RequestSnippet.java
1. Tag, Nickname 기반 Feed 검색 로직 구현
2. Tag, Nickname 기반 Feed 검색 통합 테스트
3. API 문서 업데이트
</br>
어떤 변경 사항이 있나요?
> [feat -> develop] feat - #125: TagName, Nickname 기반 Feed 검색 로직 구현 및 통합 테스트

- travel-with-me/src/main/resources/db/data-mysql.sql
1. data-mysql.sql 파일에서 Interest 테이블을 삭제하는 과정에서 java.sql.SQLIntegrityConstraintViolationException 발생. Interest를 참조하고 있는 Member_Interest 테이블을 먼저 지우고 Interest 테이블을 삭제하도록 설정
</br>
어떤 변경 사항이 있나요?
- [x] Pull Request Title을 다음 예시와 같이 작성했습니다. (e.g. [feat -> develop] feat - #1: 회원가입 기능 구현)
> fix - #142: SQLIntegrityConstraintViolationException 해결

- travel-with-me/build.gradle
- travel-with-me/src/main/resources/logback-spring.xml
</br>
어떤 변경 사항이 있나요?
- [x] Pull Request Title을 다음 예시와 같이 작성했습니다. (e.g. [feat -> develop] feat - #1: 회원가입 기능 구현)
> [feat -> develop] feat - #145: Discord에서 log 확인할 수 있도록 자동화
